app = "fly-directus-twilight-dream-3768"
primary_region = "iad"

[checks.healthCheck]
grace_period = "1m0s"
interval = "30s"
method = "get"
path = "/server/health"
port = 8_055
timeout = "10s"
type = "http"

[env]
ASSETS_TRANSFORM_MAX_CONCURRENT = "10"
CORS_ENABLED = "true"
CORS_ORIGIN = "true"
DB_CLIENT = "sqlite3"
DB_FILENAME = "/data/database/data.db"
FLY_PRIMARY_REGION = "iad"
PORT = "8055"
STORAGE_LOCAL_DRIVER = "local"
STORAGE_LOCAL_ROOT = "/data/uploads"
STORAGE_LOCATIONS = "local"

[experimental]
auto_rollback = true
cmd = ["start.sh"]
entrypoint = ["sh"]

[experimental.attached]
secrets = {}

[http_service]
auto_start_machines = true
auto_stop_machines = "suspend"
force_https = true
internal_port = 8_055
min_machines_running = 0
processes = ["app"]

[[mounts]]
destination = "/data"
source = "directus_data"

[[services]]
internal_port = 8_055
auto_start_machines = true
auto_stop_machines = "suspend"
processes = ["app"]
protocol = "tcp"

[services.concurrency]
hard_limit = 100
soft_limit = 50
type = "requests"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
