name: Backup DB
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  backup:
    name: Backup
    runs-on: ubuntu-latest
    steps:
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Start Machine
        run: flyctl machine start ${{ secrets.FLY_MACHINE_ID }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Download DB
        run: flyctl ssh sftp get -a ${{ secrets.FLY_APP_NAME}} /data/database/data.db
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Backup DB
        uses: actions/upload-artifact@v4
        with:
          name: directus_db_backup@${{ env.NOW }}
          path: data.db
          compression-level: 9
